name: docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Substreams release version"
        required: false
        type: string

  push:
    tags:
      - "v*"
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get substreams release version
        id: version
        run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            VERSION=$(curl --silent "https://api.github.com/repos/streamingfast/substreams/releases/latest" | jq -r '.tag_name | sub("^v"; "")')
          else
            VERSION=${{ github.event.inputs.version }}
          fi

          echo "::set-output name=version::$VERSION"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.version.outputs.version }}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
          build-args: |
            VERSION=${{ steps.version.outputs.version }}
